# This configuration file can be used to build and deploy the todo-backend
# quickstart on OpenShift with the Helm Chart for EAP.
build:
  contextDir: postgres
  # ref: 7.4.x
  ref: main
  uri: 'https://github.com/kabir/eap-openshift-quickstarts-wip'
  mode: s2i
  s2i:
    featurePacks:
      - org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003
    galleonLayers: cloud-server,postgresql-datasource
  env:
#    - name: ARTIFACT_DIR
#      value: todo-backend/target
#    - name: MAVEN_ARGS_APPEND
#      value: -am -pl todo-backend
    - name: POSTGRESQL_DRIVER_VERSION
      value: '42.2.19'
deploy:
  replicas: 3
  env:
    # Env vars to connect to PostgreSQL DB
    - name: POSTGRESQL_DATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: example-db
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: example-db
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: example-db
    - name: POSTGRESQL_DATASOURCE
      value: ToDos
    - name: POSTGRESQL_SERVICE_HOST
      value: example-db
    - name: POSTGRESQL_SERVICE_PORT
      value: "5432"
    # Env to avoid OOME
    - name: GC_MAX_METASPACE_SIZE
      value: "256"
    - name: GC_METASPACE_SIZE
      value: "96"