apiVersion: v1
kind: Secret
metadata:
  name: service-account-credentials
type: Opaque
stringData:
  RHOAS_SERVICE_ACCOUNT_CLIENT_ID: e08e943b-91e7-4e48-a2bc-fdd0a25b1000
  RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET: DDz5CXEV5PDg4BoU28RhFj9GEILkeVIO
  RHOAS_SERVICE_ACCOUNT_OAUTH_TOKEN_URL: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
