= Postgres Quickstart

== The Application
The `src/main` folder contains a simple application exposing a REST endpoint which allows users to post data. Posted data is stored in a database. Then there is an endpoint allowing users to get data stored in the database.

Before deploying the quickstart we need to start a database on OpenShift. Since when setting up a database on OpenShift we are dealing with sensitive information sunch as database login credentials, we will do this two ways:

. *Simple setup* - This hardcodes the username and password in the application Halm chart, as well as when starting the database. Note this is *not* recommended for production.
. *Using secrets setup* - This will first store the database credentials in an Openshift secret, and then we will reference this data from our application Helm chart. Similarly, when starting the database we will use the information from the secret.

Do not mix the steps for these two steps, they are different approaches.

Before looking at the applications we will start the database server. This will be done with hard-coded values. In a real setup this should be done via a more secure mechanism. As the focus on this quickstart is how to configure an application running in EAP on OpenShift, we will simplify this step. The aim is to have a database up and running.

== Starting the database
Fist we need to set up a PostgreSQL instance:
```shell
oc new-app --name database-server \
     --env POSTGRESQL_USER=admin \
     --env POSTGRESQL_PASSWORD=admin \
     --env POSTGRESQL_DATABASE=sampledb \
     postgresql:latest
```
This will create an OpenShift `Deployment` called `database-server` from the image `postgresql:latest`, and expose a service called `database-server`. A service is a host name that can be used internally in the cluster. In other words, from inside the OpenShift project we will be able to access our database server via `database-server` rather than needing to know the IP address of the pod(s) running it.

The `POSTGRESQL_USER`, `POSTGRESQL_PASSWORD` and `POSTGRESQL_DATABASE` environment variables used are understood by the `postgresql:latest` image and set the username/password and the name of the database to use.

The above command will start the database quickly.

== Simple setup

Make sure you have done all the link:../RUNNING_ON_OPENSHIFT.adoc#_prerequisites[prerequisites] and link:../RUNNING_ON_OPENSHIFT.adoc#_selectingcreating_a_project[selected/created a project].


=== Deploying the 'simple' setup quickstart
Install the Helm chart contained under link:./charts/helm-simple.yaml[./charts/helm-simple.yaml] to install the application into OpenShift.
[source,shell]
----
helm install postgres-simple -f charts/helm-simple.yaml jboss-eap/eap74
----
See the link:../RUNNING_ON_OPENSHIFT.adoc#_deploying_with_helm[Deploying with Helm] section for information about when the application will be ready.

=== Running the 'simple' setup application

Create a few entries in the database by running the following POST commands:
[source,shell]
----
curl -X POST https://$(oc get route postgres-simple --template='{{ .spec.host }}')/one
curl -X POST https://$(oc get route postgres-simple --template='{{ .spec.host }}')/two
----
Then we can read the entries we added
[source,shell]
----
curl https://$(oc get route postgres-simple --template='{{ .spec.host }}')
----
which should return
[source,shell]
----
["one","two"]
----

=== Explaining the 'simple' setup application configuration
link:./charts/helm-simple.yaml[./charts/helm-simple.yaml] contains the configuration for the application.

First let us examine the `build` section of the Helm chart.

It says to use the `postgres` directory under the quickstart as outlined in link:../RUNNING_ON_OPENSHIFT.adoc#_introduction_to_helm_charts[Introduction to Helm Charts].

We specify that we want to use the EAP datasources feature pack and provision the `cloud-server` and `postgresql-datasource` layers as mentioned in link:../RUNNING_ON_OPENSHIFT.adoc#_trimming_the_provisioned_server[Trimming the provisioned server] and link:../RUNNING_ON_OPENSHIFT.adoc#_adding_galleon_feature_packs[Adding Galleon Feature Packs] sections.

The `POSTGRESQL_DRIVER_VERSION` environment variable sets the version of the PostgreSQL driver as explained in link:../RUNNING_ON_OPENSHIFT.adoc#_setting_environment_variables[Setting environment variables].

In the `deploy section` we hardcode environment variables to connect to the database. The `postgresql-datasource` results in a PostgreSQL datasource being added to the server configuration. This datasource configuration, in turn, contains expressions that can be resolved from the listed environment variables.

== Using secrets setup

=== Adding our secret
link:./postgres-db-secret.yaml[openshift-secret.yaml] contains a secret called `postgres-db-secret` with base64 encoded values of the most sensitive data needed to connect to our database. See link:../RUNNING_ON_OPENSHIFT.adoc#_adding_a_secret_to_openshift[Adding a secret to OpenShift] for more information.

To add this secret, run:
[source, yaml]
----
oc apply -f postgres-db-secret.yaml
----

=== Deploying the 'using secrets' setup quickstart
Install the Helm chart contained under link:./charts/helm-secret.yaml[./charts/helm-secret.yaml] to install the application into OpenShift.
[source,shell]
----
helm install postgres-secret -f charts/helm-secret.yaml jboss-eap/eap74
----
See the link:../RUNNING_ON_OPENSHIFT.adoc#_deploying_with_helm[Deploying with Helm] section for information about when the application will be ready.

=== Running the 'using secrets' setup application

Create a few entries in the database by running the following POST commands:
[source,shell]
----
curl -X POST https://$(oc get route postgres-secret --template='{{ .spec.host }}')/one
curl -X POST https://$(oc get route postgres-secret --template='{{ .spec.host }}')/two
----
Then we can read the entries we added
[source,shell]
----
curl https://$(oc get route postgres-secret --template='{{ .spec.host }}')
----
which should return
[source,shell]
----
["one","two"]
----

=== Explaining the 'using secrets' setup application configuration
link:./charts/helm-simple.yaml[./charts/helm-simple.yaml] contains the configuration for the application.

First let us examine the `build` section of the Helm chart.

It says to use the `postgres` directory under the quickstart as outlined in link:../RUNNING_ON_OPENSHIFT.adoc#_introduction_to_helm_charts[Introduction to Helm Charts].

We specify that we want to use the EAP datasources feature pack and provision the `cloud-server` and `postgresql-datasource` layers as mentioned in link:../RUNNING_ON_OPENSHIFT.adoc#_trimming_the_provisioned_server[Trimming the provisioned server] and link:../RUNNING_ON_OPENSHIFT.adoc#_adding_galleon_feature_packs[Adding Galleon Feature Packs] sections.

The `POSTGRESQL_DRIVER_VERSION` environment variable sets the version of the PostgreSQL driver as explained in link:../RUNNING_ON_OPENSHIFT.adoc#_setting_environment_variables[Setting environment variables].

In the `deploy section` we hardcode environment variables to connect to the database. The `postgresql-datasource` results in a PostgreSQL datasource being added to the server configuration. This datasource configuration, in turn, contains expressions that can be resolved from the listed environment variables. The environment variables `POSTGRESQL_DATABASE`, `POSTGRESQL_USER` and `POSTGRESQL_PASSWORD` are set from entries in the `postgres-db-secret` secret we created earlier. See link:../RUNNING_ON_OPENSHIFT.adoc#_mapping_individual_values_from_a_configmapsecret_to_environment_variables[Mapping individual values from a ConfigMap/Secret to environment variables] for more details.

== Deleting the database

The following commands will delete the database once you are done with the quickstart.

[source,shell]
----
oc delete deployment database-server
oc delete service database-server
----

To delete the secret (for the 'using secrets' flavour of this quickstart):
[source,shell]
----
oc delete secret postgres-db-secret
----